version: '3.8'

services:
  api:
    build: .
    ports:
      - "${SERVER_PORT:-8080}:${SERVER_PORT:-8080}"
    environment:
      - SERVER_PORT=${SERVER_PORT:-8080}
      - DATABASE_URL=${DATABASE_URL:-postgres://user:password@db:5432/conference_booking?sslmode=disable}
    depends_on:
      - db
    restart: on-failure

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=${DB_USER:-user}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-password}
      - POSTGRES_DB=${DB_NAME:-conference_booking}
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

  